### ISSUE TITLE
Unable to open/edit files

### ISSUE THREAD

**Issue by ghost** [LVPlayground/pawn-editor#1]
I'm now using the latest pawncc.exe provided by Russell last night, and pawncc.exe does at least open without errors/warnings now, however, I'm still unable to open files using PawnEditor.exe. For example, I tried double-clicking AdministratorCommands.pwn -- nothing happened, same with various other files. Tried enabling/disabling compatibility mode, running as admin, etc.  

I created a screen capture to demonstrate: _removed as problem solved_

**Comment by jadegraaf** [comment]
Looks like you only downloaded the project configuration file and not the project files themselves.
Clone https://github.com/LVPlayground/playground through git or the GitHub client https://desktop.github.com. This method is easiest if you want to submit pull requests. You can also download our latest release from https://github.com/LVPlayground/playground/releases/tag/v26.0 if you just want to run the gamemode.
Once you have all the files, open LVP.ppr inside the editor.

**Comment by ghost** [comment]
Problem solved, thanks oostcoast.
